In [1]:
from pathlib import Path
import sys
import re
import pandas as pd

In [2]:
folder = Path("/Users/samiraisin/Devil_semelparity_project/store_results/18.03.2026/")

In [3]:
filenames = [f.name for f in folder.iterdir() if f.suffix == ".csv"]

In [4]:
filenames[0]

'INF1_0.0_INF2_0.1_sample_2_statistics.csv'

In [5]:
len(filenames)

92

In [6]:
m = re.search(r"^INF1_([\d.]+)_INF2_([\d.]+)_sample_(\d+)_statistics.csv$", 'INF1_0.5_INF2_0.0_sample_1_statistics.csv')

if m:
    print(m.groups())

('0.5', '0.0', '1')

In [7]:
df = pd.DataFrame(columns=["INF1", "INF2", "sample", "result"])

In [8]:
for filename in filenames:
    m = re.search(r"^INF1_([\d.]+)_INF2_([\d.]+)_sample_(\d+)_statistics.csv$", filename)
    if m:
        INF1, INF2, sample = m.groups()
        result = pd.read_csv(folder / filename)['result'].iloc[-1]
        df = pd.concat([df, pd.DataFrame([{"INF1": float(INF1), "INF2": float(INF2), "sample": int(sample), "result": result}])], ignore_index=True)

/var/folders/9q/pv4ly36x3xg6y47msgdwbk640000gn/T/ipykernel_35501/3392472778.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([{"INF1": float(INF1), "INF2": float(INF2), "sample": int(sample), "result": result}])], ignore_index=True)

In [9]:
df.head()

   INF1  INF2 sample       result
0  0.00  0.10      2   extinction
1  0.01  0.10      0   extinction
2  0.01  0.01      1   extinction
3  0.10  0.00      2  iteroparous
4  0.00  1.00      1   extinction

In [10]:
duplicates = df[df.duplicated(subset=['INF1', 'INF2', 'result'], keep=False)]

In [11]:
duplicates[duplicates['result'] == "semelparous"]

Empty DataFrame
Columns: [INF1, INF2, sample, result]
Index: []

In [12]:
df[(df['INF1'] == 0.01) & (df['INF2'] == 0.01) & (df['result'] == 'semelparous')]

Empty DataFrame
Columns: [INF1, INF2, sample, result]
Index: []

In [13]:
df[(df['result'] == 'semelparous')]

     INF1  INF2 sample       result
45  0.005  0.01      2  semelparous